# widget behavior
archive_type: monthly
show_count: true

# Miscellaneous
favicon: /favicon.ico

# Opengraph

og_latitude     : "-6.193665"
og_longitude    : "106.848558"
og_locality     : Jakarta
og_country_name : Indonesia
